services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    
    command: >
      sh -c "python wait_for_postgres.py &&
           flask run --host=0.0.0.0" 

  db:
      image: postgis/postgis:15-3.3
      restart: always
      environment:
        POSTGRES_DB: testdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Paddi_1984
      volumes:
        - ./db_init:/docker-entrypoint-initdb.d
      ports:
        - "5432:5432"
